// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFavorite = "favorite"

// Favorite mapped from table <favorite>
type Favorite struct {
	ID         int64 `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"` // id主键
	UserID     int64 `gorm:"column:user_id;type:bigint;not null" json:"user_id"`            // 用户id
	VideoID    int64 `gorm:"column:video_id;type:bigint;not null" json:"video_id"`          // 喜欢作品id
	CreateTime int64 `gorm:"column:create_time;type:bigint unsigned;autoCreateTime" json:"create_time"`
}

// TableName Favorite's table name
func (*Favorite) TableName() string {
	return TableNameFavorite
}
