// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID         int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ToUserID   int64  `gorm:"column:to_user_id;type:bigint;not null" json:"to_user_id"`                  // 该消息接收者的id
	FromUserID int64  `gorm:"column:from_user_id;type:bigint;not null" json:"from_user_id"`              // 该消息发送者的id
	Content    string `gorm:"column:content;type:varchar(255);not null" json:"content"`                  // 内容
	CreateTime int64  `gorm:"column:create_time;type:bigint unsigned;autoCreateTime" json:"create_time"` // 创建时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
